#Nome das Ações:  
Nome : Jogo da Cobra

# Controlador de tempo que será feito a atualização dos arquivos.
em :
  cronograma :
      # atualizado a cada 5 horas.
    -cron : " 0 * /5 * * * "

# Permite executar uma lista de Actions (utilizada para testes de build).
  fluxo de trabalho_dispatch :

#regras_ _
negócios :
  construir :
    executado : ubuntu-mais recente
    etapas :

    # Verifique o repositório em $GITHUB_WORKSHOP, para que seu trabalho possa acessá-lo
      - EUA : ações/checkout@v2

    # Repositório que será utilizado para gerar os arquivos.
      - usos : Platane/snk@master
        id : cobra-gif
        com :
          github_user_name : Thiago-MA97 # Seu usuário
          gif_out_path : dist/github-contribution-grid-snake.gif
          svg_out_path : dist/github-contribution-grid-snake.svg

      - executar : status do git

      # Para as atualizações.
      - nome : Enviar alterações
        usos : ad-m/github-push-action@master
        com :
          github_token : ${{ secrets.GITHUB_TOKEN }}
          ramo : mestre
          força : verdadeiro

      - EUA : crazy-max/ghaction-github-pages@v2.1.3
        com :
          # o ramo de saída que mencionamos acima
          target_branch : saída
          build_dir : dist
        ambientes :
          GITHUB_TOKEN : ${{ secrets.GITHUB_TOKEN }}
